# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kQDJqJMWBBArz3gpYqVhlazvQ-2spmD
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score

# reading the data
data = pd.read_csv("loan_approval.csv")

# checking the missing values
print("checking if the data has any missing values :")
print(data.isnull().sum())

# spliting the data into x and y

x = data.iloc[:,0:4]
y = data.iloc[:,4]

# encoding the data
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# spliting the data into training and testing
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.5, random_state = 82)

# scaling the data
scaler = StandardScaler()
x_train_scaler = scaler.fit_transform(x_train)
x_test_scaler = scaler.transform(x_test)

# performing logistic regression for predicting the data
model = LogisticRegression(penalty = "l1",solver = "liblinear",max_iter = 1000)
model.fit(x_train_scaler,y_train)

prediction = model.predict(x_test_scaler)
print("predicted data :",prediction)
print("Actual data :",y_test)

# prediction of proability
pred_prob = model.predict_proba(x_test_scaler)
print("\nprediction of probability :",pred_prob)

# confusion_matrix
confusion = confusion_matrix(y_test,prediction)
print("\nconfusion_matrix :",confusion)

# accuracy_score
accuracy = accuracy_score(y_test,prediction)
print("\naccuracy_score :",accuracy)

# precision_score
precision = precision_score(y_test,prediction)
print("\nprecision_score :",precision)

# recall_score
recall = recall_score(y_test,prediction)
print("\nrecall_score :",recall)

# f1_score
f1 = f1_score(y_test,prediction)
print("\nf1_score :",f1)

# log_loss
loss = log_loss(y_test,pred_prob)
print("\nlog_loss :",loss)

# roc_auc_score
roc_auc = roc_auc_score(y_test,pred_prob[:, 1])
print("\nroc_auc_score :",roc_auc)


# visualization of Actual Data and Predicted Data
plt.scatter(y_test, prediction)

plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")

plt.xticks([0, 1])
plt.yticks([0, 1])

plt.show()

# visualization of probability and showing the treshold explanation
probability = pred_prob[:, 1]

plt.scatter(
    range(len(probability)),
    probability
)

plt.axhline(
    y=0.5,
    linestyle="--"
)

plt.xlabel("Test Sample")
plt.ylabel("Probability of Loan Approval")
plt.title("Logistic Regression Probability")
plt.legend('treshold',loc = 'center')
plt.style.use("ggplot")
plt.show()
